// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAHYEU6uJMlz_X2Cdjl6mvNUQoIxJ0c6Q',
    appId: '1:942840824629:web:2e5725344b9588b3b9027c',
    messagingSenderId: '942840824629',
    projectId: 'task-management-system-7eacc',
    authDomain: 'task-management-system-7eacc.firebaseapp.com',
    storageBucket: 'task-management-system-7eacc.appspot.com',
    measurementId: 'G-XC5RCRZFPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmVZS8JIHv5089d2dky-cw4xBwLdD2yro',
    appId: '1:942840824629:android:f033d4c2d9b21c89b9027c',
    messagingSenderId: '942840824629',
    projectId: 'task-management-system-7eacc',
    storageBucket: 'task-management-system-7eacc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKyrcC5p31TJ1TM6Gpvf-Cxh5ffeCrYI8',
    appId: '1:942840824629:ios:32e0c9f97d993214b9027c',
    messagingSenderId: '942840824629',
    projectId: 'task-management-system-7eacc',
    storageBucket: 'task-management-system-7eacc.appspot.com',
    iosBundleId: 'com.example.taskManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKyrcC5p31TJ1TM6Gpvf-Cxh5ffeCrYI8',
    appId: '1:942840824629:ios:32e0c9f97d993214b9027c',
    messagingSenderId: '942840824629',
    projectId: 'task-management-system-7eacc',
    storageBucket: 'task-management-system-7eacc.appspot.com',
    iosBundleId: 'com.example.taskManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAHYEU6uJMlz_X2Cdjl6mvNUQoIxJ0c6Q',
    appId: '1:942840824629:web:aa75168b0e85e7dab9027c',
    messagingSenderId: '942840824629',
    projectId: 'task-management-system-7eacc',
    authDomain: 'task-management-system-7eacc.firebaseapp.com',
    storageBucket: 'task-management-system-7eacc.appspot.com',
    measurementId: 'G-KF5MTX0GXL',
  );
}
